#!/bin/sh
# AgentVault layer-2 scrub hook (generated by `av init --agent generic`).
#
# Pipes stdin through `av scrub`, which forwards to the AgentVault daemon for
# redaction: session values and gitleaks-detected secrets become {{AV:NAME}} /
# {{AV:REDACTED:<rule>}} before the text reaches the agent's context.
#
# Wire this into your agent on EVERY context-ingress channel (see AGENTVAULT.md).
#
# AV_NO_PROMPT=1 marks this as the AGENT path: a locked vault returns exit 69 (pause for
# a human to unlock) instead of blocking the agent on an on-demand Touch ID. Export it so
# every `av` call the agent makes (av run / av read / av add) inherits the opt-out.
export AV_NO_PROMPT=1
exec av scrub
