#!/bin/sh
# AgentVault layer-2 scrub hook (generated by `av init --agent generic`).
#
# Pipes stdin through `av scrub`, which forwards to the AgentVault daemon for
# redaction: session values and gitleaks-detected secrets become {{AV:NAME}} /
# {{AV:REDACTED:<rule>}} before the text reaches the agent's context.
#
# Wire this into your agent on EVERY context-ingress channel (see AGENTVAULT.md).
exec av scrub
